name: Go

on: [workflow_dispatch]

jobs:

  build:    
    runs-on: ubuntu-latest
    steps: 

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out into Go module directory
      uses: actions/checkout@v2
     
    - name: Build        
      run: make build

    - name: vendor mod step     
      run: go mod vendor

    - name: Loop Through Files
      run: |                
        for zone in $(ls ./zones/)
        do
          echo $zone
          go run main.go -domain $zone -zone-file ./zones/$zone >> ./tfzones/$zone.tf
        done;

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com" 

    - name: Git commit and push
      run: |
        git add .
        git commit -m "Add generated files"
        git push origin master

    #- name: Test2
    #  run: go run main.go -domain gallylwtestdomain.com -zone-file ./zones/gallylwtestdomain.com > gallylwtestdomain.com.tf

   


    
    
